DROP DATABASE IF EXISTS EXERCICIO19;

CREATE DATABASE EXERCICIO19;

USE EXERCICIO19;

CREATE TABLE MEDICO (
ID_MEDICO INT NOT NULL,
NOME VARCHAR (45),
PRIMARY KEY (ID_MEDICO)
);
CREATE TABLE PACIENTE (
ID_PACIENTE INT NOT NULL,
NOME VARCHAR (45),
PRIMARY KEY (ID_PACIENTE)
);
CREATE TABLE CONSULTA (
ID_MEDICO  INT NOT NULL,
ID_PACIENTE INT NOT NULL,
DATA_DA_CONSULTA DATE,
PRIMARY KEY (ID_MEDICO , ID_PACIENTE),
FOREIGN KEY (ID_MEDICO ) REFERENCES MEDICO (ID_MEDICO),
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);